### ISSUE TITLE
Select random Provider to provide captcha for Dapp User

### ISSUE THREAD

**Issue by forgetso** [prosopo-io/procaptcha#17]
This should make use of the `getRandomActiveProvider` function in the contract. The `DApp User` should be required to do a contract query to get the `Provider`, connecting to a node in the process (hopefully some kind of light node in the browser).

## Assumptions

- provider will expose contract helper functions via a package called contract

```
provider
    src
        packages
            contract
            providerApi
            providerDb
            etc.
```

- proCaptcha will be able to import `@prosopo/contract` from workspace
- frontend will be composed of JS UI that can be integrated into various projects (React, Django, etc.)

- [ ] use `create-react-app` and work out how to connect an account to the local node (check out polkadot/apps and the polkadot.js extension for an example of this)
- [ ] connect to the contract via the `@prosopo/contract` package
- [ ] get a random provider

**Comment by vinceferro** [comment]
Design consideration:
The provider there is only exposing reusable functionalities to interact with the contract

**Comment by forgetso** [comment]
Discussed with @vinceferro and decided to move tasks to contract but keep everything else in provider

### @prosopo/contract

- All JS tasks related to contract

### @prosopo/provider-core

- API
- image server
- environment
- db
...anything else the provider needs

Eventually

### @prosopo/provider-db
- mongo
- postgres
- ipfs
